version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: "/bin/sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - "./shop:/shop/shop"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 15433:5433
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
volumes:
  db_data: