version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shop:/shop
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 15433:5433
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - .:/app
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: .
    environment:
      BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A shop worker -l info
    volumes:
      - ./shop:/shop
    depends_on:
      - redis
  flower:
    restart: always
    build:
      context: .
    environment:
      BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: celery -A shop flower
    volumes:
      - ./shop:/shop
    ports:
      - "5566:5555"
    depends_on:
      - celery
      - redis
volumes:
  pgdata: