# Generated by Django 4.2.5 on 2023-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'price'], name='ecoshop_pro_name_a90aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['amount'], name='amount_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', '-amount'], name='price_amount_idx'),
        ),
    ]
