# Generated by Django 4.2.5 on 2023-10-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('inn', models.PositiveIntegerField()),
                ('product', models.ManyToManyField(to='ecoshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('product', models.ManyToManyField(to='ecoshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(default='default review', max_length=300)),
                ('author', models.CharField(max_length=30)),
                ('reviews_time', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='PassportShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.PositiveIntegerField()),
                ('passport_series', models.CharField(max_length=5)),
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.shipper')),
            ],
        ),
    ]
