# Generated by Django 4.2.5 on 2023-10-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_product_ecoshop_pro_name_a90aa2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='amount_idx',
        ),
    ]
