# Generated by Django 4.2.5 on 2023-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0003_remove_product_amount_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruit'), ('VG', 'Vegetable'), ('ML', 'Milk products'), ('MT', 'Meat'), ('TC', 'Tea and coffee'), ('FS', 'Fish'), ('AL', 'Alcohol')], max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='perfect products', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
