# Generated by Django 4.2.5 on 2023-11-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0004_alter_product_options_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинки'),
        ),
    ]
